#!/bin/bash
APP_NAME="TheInsider Auth"

usage() {
    printf "################### TheInsider Auth ###################\n\n"
    printf "To add a service:\t mimier add gojek secrettoken\n"
    printf "\t\t\t mimier save gojek secrettoken\n\n"
    printf "To delete service:\t mimier del gojek\n"
    printf "\t\t\t mimier delete gojek\n\n"
    printf "To generate Otp:\t mimier gen gojek\n"
    printf "\t\t\t mimier generate gojek\n\n"
}


cmd_add() {
    security add-generic-password -a $1 -s "$APP_NAME" -w $2
}

cmd_del() {
    security delete-generic-password -a $1 -s "$APP_NAME"
}

cmd_gen() {
    otpkey=`security find-generic-password -a $1 -s "$APP_NAME" -w`
    otp=`/usr/local/bin/oathtool --totp -b $otpkey`
    echo $otp | tr -d '\n' | pbcopy
}

if [ "$#" -gt 3 ]; then
    echo "Invalid Arguments"
    usage
    exit 1
elif [ "$#" -eq 3 ]; then
    if [ "$1" == "add" ] || [ "$1" == "save" ]; then
        cmd_add $2 $3
        exit 0
    else
        echo "Invalid Arguments"
        usage
        exit 1
    fi
elif [ "$#" -eq 2 ]; then
    if [ "$1" == "gen" ] || [ "$1" == "generate" ]; then
        cmd_gen $2
        exit 0
    elif [ "$1" == "del" ] || [ "$1" == "delete" ]; then
        cmd_del $2
    else
        echo "Invalid Arguments"
        usage
        exit 1
    fi
elif [ "$#" -eq 1 ]; then
    echo "Invalid Arguments"
    usage
    exit 1
else
    usage
    exit 0
fi

