#!/bin/bash
APP_NAME="TheInsider Auth"

usage() {
    printf "################### TheInsider Auth ###################\n\n"
    printf "To add a service:\t mimier add gojek secrettoken\n"
    printf "To delete service:\t mimier del gojek\n"
    printf "To print OTP:\t\t mimier get gojek\n"
    printf "To copy OTP:\t\t mimier copy gojek\n"
}


cmd_add() {
    security add-generic-password -a $1 -s "$APP_NAME" -w $2
}

cmd_del() {
    security delete-generic-password -a $1 -s "$APP_NAME"
}

cmd_gen() {
    local otpkey=`security find-generic-password -a $1 -s "$APP_NAME" -w`
    local otp=`/usr/local/bin/oathtool --totp -b $otpkey`
    echo $otp | tr -d '\n'
}

cmd_get() {
    local otp=$(cmd_gen $1)
    echo $otp | tr -d '\n'
}

cmd_copy() {
    local otp=$(cmd_gen $1)
    echo $otp | tr -d '\n' | pbcopy
}

if [ "$#" -gt 3 ]; then
    echo "Invalid Arguments"
    usage
    exit 1
elif [ "$#" -eq 3 ]; then
    if [ "$1" == "add" ]; then
        cmd_add $2 $3
        exit 0
    else
        echo "Invalid Arguments"
        usage
        exit 1
    fi
elif [ "$#" -eq 2 ]; then
    if [ "$1" == "get" ]; then
        cmd_get $2
        exit 0
    elif [ "$1" == "copy" ]; then
        cmd_copy $2
        exit 0
    elif [ "$1" == "del" ]; then
        cmd_del $2
        exit 0
    else
        echo "Invalid Arguments"
        usage
        exit 1
    fi
elif [ "$#" -eq 1 ]; then
    echo "Invalid Arguments"
    usage
    exit 1
else
    usage
    exit 0
fi
